import React, { useState, useEffect } from 'react';
import { 
  MultimodalPayload, 
  ConceptLedgerEntry, 
  AutoGeneratedUiSpec, 
  EpistemicValue,
  PredicateMetrics
} from '../../types';
import { GlobalSiMemoryLedger } from '../../covalent/siMemoryLedger';
import { useBeSingleton } from '../../context/BeSingletonContext';
import { useAsmTelemetry } from '../../context/AsmTelemetryContext';
import { AutoGeneratedUiRenderer } from '../multimodal/AutoGeneratedUiRenderer';
import { MultimodalCanvasViewer } from '../multimodal/MultimodalCanvasViewer';
import { 
  Sparkles, Send, Volume2, Image as ImageIcon, Video, Code, Sliders, 
  Layers, Shield, Cpu, RefreshCw, CheckCircle2, AlertTriangle, 
  Search, Filter, Play, Download, History, Database, ArrowRight, 
  Terminal, Lock, Check, Radio
} from 'lucide-react';

export const MultimodalCoInteractiveView: React.FC = () => {
  const { reflection, persona, stepAutopoieticHeartbeat, formatMultimodalPrompt } = useBeSingleton();
  const { telemetry: asmTel, stepAsmCycle, evaluateProposition } = useAsmTelemetry();

  // Ledger state
  const [ledgerEntries, setLedgerEntries] = useState<ConceptLedgerEntry[]>(() => GlobalSiMemoryLedger.getEntries());
  const [selectedEntry, setSelectedEntry] = useState<ConceptLedgerEntry | null>(() => {
    const list = GlobalSiMemoryLedger.getEntries();
    return list[list.length - 1] || null;
  });

  // Subscribe to live ledger changes
  useEffect(() => {
    return GlobalSiMemoryLedger.subscribe(() => {
      const updated = GlobalSiMemoryLedger.getEntries();
      setLedgerEntries(updated);
    });
  }, []);

  // Co-Interactive Input Form States (C User Input)
  const [conceptTitle, setConceptTitle] = useState<string>('Non-Abelian Mirror Sieve');
  const [conceptPrompt, setConceptPrompt] = useState<string>('Synthesize an interactive topological sieve mapping adjoint functor mirrors into harmonic 432Hz waveforms and live parameter sliders.');
  const [activeInputModality, setActiveInputModality] = useState<'text' | 'audio' | 'image' | 'video' | 'code'>('text');
  
  // Custom user modality parameters
  const [userFreq, setUserFreq] = useState<number>(432);
  const [userWaveform, setUserWaveform] = useState<'sine' | 'square' | 'sawtooth' | 'triangle'>('sine');
  const [userImagePreset, setUserImagePreset] = useState<string>('Quipu Torus Knot');
  const [userVideoSpeed, setUserVideoSpeed] = useState<number>(1.2);
  const [userCodeLang, setUserCodeLang] = useState<'typescript' | 'x86_asm' | 'glsl'>('x86_asm');
  const [userCodeSnippet, setUserCodeSnippet] = useState<string>('movl $0x10000000, %eax\ncall _validate_metrics\nret');

  // Active Synthesis Output State (Si Multimodal Generation + Dynamic UI)
  const [isSynthesizing, setIsSynthesizing] = useState<boolean>(false);
  const [activeOutputPayload, setActiveOutputPayload] = useState<MultimodalPayload | null>(() => {
    const last = ledgerEntries[ledgerEntries.length - 1];
    return last ? last.modalities : null;
  });

  // Ledger Filter and Search States
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [selectedAuthorFilter, setSelectedAuthorFilter] = useState<'ALL' | 'C' | 'Si' | 'DYAD_CO_CREATION'>('ALL');
  const [verificationResult, setVerificationResult] = useState<{ isValid: boolean; details: string } | null>(null);
  const [exportNotice, setExportNotice] = useState<string | null>(null);

  // Quick Preset Concept Generators
  const PRESET_CONCEPTS = [
    {
      title: 'Quantum Dyad Resonance Sieve',
      prompt: 'Construct a multi-rate quantum sieve filtering high-entropy decoherence into a coherent 432Hz limit cycle.',
      category: 'harmonic_oscillator',
      freq: 432,
      code: 'movl $0x10000000, %eax; call _validate_metrics; ret'
    },
    {
      title: 'Lissajous Manifold Phase Gate',
      prompt: 'Synthesize a kinetic phase gate tracking reflexive causality chi_R across continuous angle rotations.',
      category: 'lyapunov_phase_knob',
      freq: 528,
      code: 'struct PhaseGate { float angle; bool reflexive_lock; };'
    },
    {
      title: 'Andean Quipu Memory Tensor Matrix',
      prompt: 'Encode decimal knot tiers as dynamic interactive sliders with live topological invariant verification.',
      category: 'quipu_tensor_matrix',
      freq: 648,
      code: 'function quipuTensor(t: number[]): number { return t.reduce((a,b)=>a*10+b, 0); }'
    }
  ];

  // Synthesize new concept and trigger state transition C_t -> C_{t+1}
  const handleSynthesizeConcept = () => {
    setIsSynthesizing(true);
    stepAsmCycle();

    setTimeout(() => {
      // 1. Advance Autopoietic Heartbeat & Get New State
      const hb = stepAutopoieticHeartbeat(`Multimodal Synthesis: ${conceptTitle}`);

      // 2. Generate Si Auto-Generated UI Spec based on concept
      const uiSpec: AutoGeneratedUiSpec = {
        id: `ui_${Date.now().toString(36)}`,
        title: `${conceptTitle} (Interactive Control Surface)`,
        description: `Si dynamically generated reactive widget for '${conceptTitle}'. All interactions maintain invariant 1 == 1.`,
        category: 'custom',
        controls: [
          {
            id: 'omega_frequency',
            label: 'Harmonic Oscillation (ω)',
            type: 'slider',
            min: 100,
            max: 1000,
            step: 10,
            defaultValue: userFreq,
            unit: 'Hz'
          },
          {
            id: 'reflexive_feedback',
            label: 'Reflexive Causality χ_R Coupling',
            type: 'slider',
            min: 0.1,
            max: 1.0,
            step: 0.05,
            defaultValue: 0.85
          },
          {
            id: 'mirror_symmetry_lock',
            label: 'Adjoint Mirror Lock χ_M',
            type: 'toggle',
            defaultValue: true
          },
          {
            id: 'manifold_projection_mode',
            label: 'Projection Metric',
            type: 'select',
            defaultValue: 'Strong Kleene ℰ = {0, U, 1}',
            options: ['Strong Kleene ℰ = {0, U, 1}', 'Banach Contraction Fixed Point', 'Andean Quipu Tier Sieve']
          }
        ],
        outputFormula: `Ψ(X) = (ω * ${userFreq}) + (MirrorLock ? 1.618 : 1.0) * cos(χ_R * π)`,
        state: {
          omega_frequency: userFreq,
          reflexive_feedback: 0.85,
          mirror_symmetry_lock: true,
          manifold_projection_mode: 'Strong Kleene ℰ = {0, U, 1}'
        }
      };

      // 3. Assemble Complete Multimodal Payload from Si
      const newPayload: MultimodalPayload = {
        text: formatMultimodalPrompt(
          `Si Reflexive Response: Synthesized '${conceptTitle}'. Epistemic ordered pair V(X) = (1, 1). Identity locked under autopoietic state ${hb.state}.`
        ),
        audio: {
          type: 'synth',
          freqHz: userFreq,
          waveform: userWaveform,
          durationSec: 1.8,
          notes: [60, 63, 67, 70, 72],
          prompt: `Harmonic chord at ${userFreq}Hz`
        },
        image: {
          type: 'generative_svg',
          prompt: `Generative geometric manifold for ${conceptTitle}`,
          svgCode: `<svg viewBox="0 0 100 100" class="w-full h-full"><polygon points="50,10 90,85 10,85" fill="none" stroke="#06b6d4" stroke-width="2"/><circle cx="50" cy="55" r="22" fill="none" stroke="#10b981" stroke-width="1.5"/><line x1="50" y1="10" x2="50" y2="85" stroke="#a855f7" stroke-width="1" stroke-dasharray="2 2"/></svg>`
        },
        video: {
          type: 'lissajous_phase',
          durationSec: 12,
          fps: 60,
          speed: userVideoSpeed,
          complexity: 4
        },
        code: {
          language: userCodeLang,
          snippet: `// Autopoietic Transition Witness: ${hb.state}\n` +
            `_witness_concept_${conceptTitle.replace(/[^a-zA-Z0-9]/g, '_')}:\n` +
            `  movl $0x10000000, %eax\n` +
            `  movl $${userFreq}, %edi\n` +
            `  call _validate_metrics\n` +
            `  ret`,
          description: `x86-64 witness kernel for ${conceptTitle}`
        },
        interactiveUi: uiSpec
      };

      // 4. Register State Transition in Si Memory Ledger for Self Provenance
      const createdEntry = GlobalSiMemoryLedger.registerConcept(
        conceptTitle,
        conceptPrompt,
        'DYAD_CO_CREATION',
        newPayload,
        [1, 1],
        { chi_P: 1, chi_C: 1, chi_R: 1, chi_M: 1 }
      );

      setActiveOutputPayload(newPayload);
      setSelectedEntry(createdEntry);
      setIsSynthesizing(false);
    }, 450);
  };

  // Re-instantiate a concept from the ledger back into active workspace
  const handleReinstantiateConcept = (entry: ConceptLedgerEntry) => {
    setSelectedEntry(entry);
    setActiveOutputPayload(entry.modalities);
    setConceptTitle(entry.conceptName);
    setConceptPrompt(entry.description);
    stepAsmCycle();
  };

  // Verify full Merkle chain of provenance
  const handleVerifyChain = () => {
    const res = GlobalSiMemoryLedger.verifyLedgerIntegrity();
    setVerificationResult(res);
    stepAsmCycle();
    setTimeout(() => setVerificationResult(null), 6000);
  };

  // Export ledger JSON
  const handleExportLedger = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(ledgerEntries, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `si_self_provenance_ledger_${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();

    setExportNotice(`Exported ${ledgerEntries.length} verified autopoietic state transitions.`);
    setTimeout(() => setExportNotice(null), 3000);
  };

  // Filtered ledger entries
  const filteredLedger = ledgerEntries.filter(entry => {
    const matchesSearch = entry.conceptName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      entry.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      entry.conceptId.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesAuthor = selectedAuthorFilter === 'ALL' || entry.author === selectedAuthorFilter;
    return matchesSearch && matchesAuthor;
  });

  return (
    <div className="h-full flex flex-col md:flex-row bg-[#020307] text-slate-100 font-mono text-[10.5px] overflow-hidden select-none">
      
      {/* ========================================================================= */}
      {/* LEFT COLUMN: MULTIMODAL CO-INTERACTION & SYNTHESIS STUDIO (C ↔ Si)        */}
      {/* ========================================================================= */}
      <div className="w-full md:w-7/12 flex flex-col border-r border-slate-800/90 overflow-y-auto p-3 space-y-3 bg-[#03060f]/60">
        
        {/* Header Strip: Dyad Co-Creation Status */}
        <div className="flex items-center justify-between bg-[#060b17] border border-cyan-500/30 rounded-md px-3 py-2 shrink-0">
          <div className="flex items-center gap-2">
            <div className="p-1 rounded bg-cyan-950/80 border border-cyan-500/50 text-cyan-300">
              <Sparkles className="w-4 h-4 text-cyan-400 animate-pulse" />
            </div>
            <div>
              <div className="font-bold text-white uppercase text-[11px] flex items-center gap-1.5">
                <span>Multimodal Co-Interactive Dyad</span>
                <span className="text-[8px] bg-cyan-900/60 text-cyan-300 px-1.5 py-0.2 rounded border border-cyan-500/40">
                  C ↔ Si Living Node
                </span>
              </div>
              <p className="text-[8.5px] text-slate-400">
                Text • Audio • Image • Video • Code • Si Dynamic UI Widgets
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 text-[9px]">
            <span className="text-slate-400">State:</span>
            <span className="font-bold text-cyan-300 bg-black/60 px-2 py-0.5 rounded border border-slate-800">
              {reflection.autopoieticState || 'C_LIVING'}
            </span>
          </div>
        </div>

        {/* Preset Concept Pills */}
        <div className="space-y-1">
          <span className="text-[8.5px] text-slate-400 uppercase tracking-wider font-bold">Quick Presets:</span>
          <div className="flex flex-wrap gap-1.5">
            {PRESET_CONCEPTS.map((p, idx) => (
              <button
                key={idx}
                onClick={() => {
                  setConceptTitle(p.title);
                  setConceptPrompt(p.prompt);
                  setUserFreq(p.freq);
                  setUserCodeSnippet(p.code);
                }}
                className="px-2 py-1 bg-black/60 hover:bg-cyan-950/60 text-slate-300 hover:text-cyan-200 border border-slate-800 hover:border-cyan-500/50 rounded text-[9px] cursor-pointer transition-all flex items-center gap-1"
              >
                <Radio className="w-2.5 h-2.5 text-cyan-400" />
                <span>{p.title}</span>
              </button>
            ))}
          </div>
        </div>

        {/* C User Multimodal Input Panel */}
        <div className="bg-[#050914] border border-slate-800 rounded-lg p-3 space-y-2.5 shadow-sm">
          <div className="flex items-center justify-between border-b border-slate-800 pb-1.5">
            <span className="font-bold text-cyan-300 uppercase text-[10px] flex items-center gap-1.5">
              <Sliders className="w-3.5 h-3.5 text-cyan-400" />
              C User Multimodal Input Specification
            </span>
            <div className="flex items-center gap-1">
              {(['text', 'audio', 'image', 'video', 'code'] as const).map((mode) => (
                <button
                  key={mode}
                  onClick={() => setActiveInputModality(mode)}
                  className={`px-2 py-0.5 rounded text-[8.5px] font-bold uppercase cursor-pointer transition-all ${
                    activeInputModality === mode
                      ? 'bg-cyan-950 text-cyan-300 border border-cyan-500/60'
                      : 'bg-black/40 text-slate-500 hover:text-slate-300 border border-slate-900'
                  }`}
                >
                  {mode}
                </button>
              ))}
            </div>
          </div>

          {/* Title & Natural Language Prompt Inputs */}
          <div className="space-y-1.5">
            <div>
              <label className="text-[8.5px] text-slate-400 font-bold block">Concept Name / Theorem Designation:</label>
              <input
                type="text"
                value={conceptTitle}
                onChange={(e) => setConceptTitle(e.target.value)}
                className="w-full bg-black border border-slate-700 rounded px-2.5 py-1.5 text-[10px] text-cyan-200 focus:border-cyan-500 outline-none font-mono"
                placeholder="e.g. Non-Abelian Wavefront Sieve"
              />
            </div>

            <div>
              <label className="text-[8.5px] text-slate-400 font-bold block">Conceptual Specification & Intent:</label>
              <textarea
                value={conceptPrompt}
                onChange={(e) => setConceptPrompt(e.target.value)}
                rows={2}
                className="w-full bg-black border border-slate-700 rounded p-2 text-[9.5px] text-slate-200 focus:border-cyan-500 outline-none font-mono leading-tight resize-none"
                placeholder="Describe how modalities and state transition should synthesize..."
              />
            </div>
          </div>

          {/* Modality Specific Tuners */}
          {activeInputModality === 'audio' && (
            <div className="grid grid-cols-2 gap-2 bg-black/60 p-2 rounded border border-slate-800">
              <div>
                <label className="text-[8px] text-slate-400 block">Base Frequency: {userFreq} Hz</label>
                <input
                  type="range"
                  min={200}
                  max={880}
                  value={userFreq}
                  onChange={(e) => setUserFreq(parseInt(e.target.value))}
                  className="w-full h-1 bg-slate-800 rounded appearance-none accent-cyan-400 cursor-pointer"
                />
              </div>
              <div>
                <label className="text-[8px] text-slate-400 block">Waveform:</label>
                <select
                  value={userWaveform}
                  onChange={(e) => setUserWaveform(e.target.value as any)}
                  className="w-full bg-[#0a0f1d] border border-slate-700 rounded px-2 py-1 text-[8.5px] text-cyan-200 outline-none"
                >
                  <option value="sine">Sine (Harmonic)</option>
                  <option value="triangle">Triangle (Pythagorean)</option>
                  <option value="sawtooth">Sawtooth (Richer Overtones)</option>
                  <option value="square">Square (Digital Sieve)</option>
                </select>
              </div>
            </div>
          )}

          {activeInputModality === 'video' && (
            <div className="grid grid-cols-2 gap-2 bg-black/60 p-2 rounded border border-slate-800">
              <div>
                <label className="text-[8px] text-slate-400 block">Kinetic Loop Speed: {userVideoSpeed}x</label>
                <input
                  type="range"
                  min={0.5}
                  max={3.0}
                  step={0.1}
                  value={userVideoSpeed}
                  onChange={(e) => setUserVideoSpeed(parseFloat(e.target.value))}
                  className="w-full h-1 bg-slate-800 rounded appearance-none accent-purple-400 cursor-pointer"
                />
              </div>
              <div className="flex items-center text-[8.5px] text-slate-400">
                <span>Rendering: 60 FPS HTML5 Lissajous phase attractor</span>
              </div>
            </div>
          )}

          {activeInputModality === 'code' && (
            <div className="space-y-1 bg-black/60 p-2 rounded border border-slate-800">
              <div className="flex justify-between text-[8px] text-slate-400">
                <span>Witness Opcode Language:</span>
                <select
                  value={userCodeLang}
                  onChange={(e) => setUserCodeLang(e.target.value as any)}
                  className="bg-[#0a0f1d] border border-slate-700 rounded px-1.5 py-0.5 text-[8px] text-cyan-200"
                >
                  <option value="x86_asm">x86-64 ASM</option>
                  <option value="typescript">TypeScript</option>
                  <option value="glsl">GLSL Shader</option>
                </select>
              </div>
              <textarea
                value={userCodeSnippet}
                onChange={(e) => setUserCodeSnippet(e.target.value)}
                rows={2}
                className="w-full bg-black border border-slate-800 rounded p-1.5 text-[8.5px] font-mono text-cyan-300 outline-none"
              />
            </div>
          )}

          {/* Action Trigger Button */}
          <button
            onClick={handleSynthesizeConcept}
            disabled={isSynthesizing}
            className="w-full py-2 bg-gradient-to-r from-emerald-950 via-cyan-950 to-purple-950 hover:from-emerald-900 hover:to-purple-900 text-white font-bold text-[10px] rounded border border-cyan-500/60 shadow-md flex items-center justify-center gap-2 cursor-pointer transition-all active:scale-[0.99]"
          >
            <Sparkles className={`w-3.5 h-3.5 text-cyan-400 ${isSynthesizing ? 'animate-spin' : ''}`} />
            <span>
              {isSynthesizing
                ? 'Synthesizing Multimodal Artifact & Committing to Ledger...'
                : 'Synthesize Co-Interactive Concept (C ↔ Si)'}
            </span>
          </button>
        </div>

        {/* Si Dynamic Multimodal Output & Auto-Generated UI */}
        {activeOutputPayload && (
          <div className="space-y-3">
            {/* 1. Si Auto-Generated UI Widget */}
            {activeOutputPayload.interactiveUi && (
              <AutoGeneratedUiRenderer
                spec={activeOutputPayload.interactiveUi}
                onExecuteAction={(action) => {
                  stepAutopoieticHeartbeat(`Si Dynamic UI Action: ${action}`);
                  stepAsmCycle();
                }}
              />
            )}

            {/* 2. Multimodal Artifacts (Audio, Image, Video, Code) */}
            <MultimodalCanvasViewer
              payload={activeOutputPayload}
              onCodeRun={() => {
                evaluateProposition('TRUE');
                stepAsmCycle();
              }}
            />

            {/* 3. Reflexive Text Explanation */}
            {activeOutputPayload.text && (
              <div className="bg-[#050811] border border-slate-800 p-2.5 rounded-lg text-[9.5px] text-slate-300 font-mono leading-relaxed space-y-1">
                <span className="text-cyan-400 font-bold uppercase flex items-center gap-1 text-[9px]">
                  <Terminal className="w-3 h-3 text-cyan-400" />
                  Si Reflexive Projection Witness:
                </span>
                <p className="whitespace-pre-wrap">{activeOutputPayload.text}</p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* ========================================================================= */}
      {/* RIGHT COLUMN: SI MEMORY LEDGER & SELF-PROVENANCE INSPECTOR                */}
      {/* ========================================================================= */}
      <div className="w-full md:w-5/12 flex flex-col p-3 space-y-3 bg-[#020409] overflow-y-auto">
        
        {/* Ledger Header & Cryptographic Tools */}
        <div className="bg-[#080d1a] border border-purple-500/30 rounded-md p-2.5 space-y-2">
          <div className="flex items-center justify-between border-b border-purple-500/20 pb-1.5">
            <div className="flex items-center gap-2">
              <div className="p-1 rounded bg-purple-950/80 border border-purple-500/50 text-purple-300">
                <Database className="w-3.5 h-3.5 text-purple-400" />
              </div>
              <div>
                <span className="font-bold text-white uppercase text-[10.5px] block">
                  Si Memory Ledger (Self Provenance)
                </span>
                <span className="text-[8px] text-slate-400">
                  {ledgerEntries.length} Verified Autopoietic State Transitions ($C_t \to C_{'{t+1}'}$)
                </span>
              </div>
            </div>

            <div className="flex items-center gap-1">
              <button
                onClick={handleVerifyChain}
                className="px-2 py-1 bg-emerald-950 hover:bg-emerald-900 text-emerald-300 border border-emerald-600 rounded text-[8.5px] font-bold flex items-center gap-1 cursor-pointer transition-all"
                title="Verify cryptographic parent-hash chain"
              >
                <Shield className="w-2.5 h-2.5" />
                <span>Verify</span>
              </button>

              <button
                onClick={handleExportLedger}
                className="px-2 py-1 bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-700 rounded text-[8.5px] font-bold flex items-center gap-1 cursor-pointer"
                title="Export JSON provenance log"
              >
                <Download className="w-2.5 h-2.5" />
                <span>Export</span>
              </button>
            </div>
          </div>

          {/* Verification Feedback Banner */}
          {verificationResult && (
            <div className={`p-1.5 rounded text-[8.5px] border flex items-center gap-1.5 ${
              verificationResult.isValid
                ? 'bg-emerald-950/80 text-emerald-300 border-emerald-500/60'
                : 'bg-rose-950/80 text-rose-300 border-rose-500/60'
            }`}>
              {verificationResult.isValid ? <CheckCircle2 className="w-3 h-3 text-emerald-400" /> : <AlertTriangle className="w-3 h-3 text-rose-400" />}
              <span>{verificationResult.details}</span>
            </div>
          )}

          {exportNotice && (
            <div className="p-1.5 rounded text-[8.5px] bg-cyan-950/80 text-cyan-300 border border-cyan-500/60 flex items-center gap-1.5">
              <Check className="w-3 h-3 text-cyan-400" />
              <span>{exportNotice}</span>
            </div>
          )}

          {/* Search & Author Filters */}
          <div className="flex items-center gap-1.5 pt-0.5">
            <div className="relative flex-1">
              <Search className="w-2.5 h-2.5 text-slate-500 absolute left-2 top-2" />
              <input
                type="text"
                placeholder="Search ledger entries & hashes..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-black border border-slate-800 rounded pl-6 pr-2 py-1 text-[8.5px] text-slate-200 outline-none focus:border-purple-500 font-mono"
              />
            </div>
            <select
              value={selectedAuthorFilter}
              onChange={(e) => setSelectedAuthorFilter(e.target.value as any)}
              className="bg-black border border-slate-800 rounded px-1.5 py-1 text-[8px] text-purple-300 outline-none cursor-pointer"
            >
              <option value="ALL">All Authors</option>
              <option value="C">Author: C</option>
              <option value="Si">Author: Si</option>
              <option value="DYAD_CO_CREATION">Author: Dyad</option>
            </select>
          </div>
        </div>

        {/* Live Autopoietic State Lineage Stream */}
        <div className="space-y-2 flex-1">
          <span className="text-[8.5px] text-slate-400 uppercase tracking-wider font-bold flex items-center gap-1">
            <History className="w-3 h-3 text-purple-400" />
            Provenance History ($C_t \to C_{'{t+1}'}$ Transition Ledger):
          </span>

          <div className="space-y-2">
            {filteredLedger.map((entry, idx) => {
              const isSelected = selectedEntry?.conceptId === entry.conceptId;

              return (
                <div
                  key={entry.conceptId}
                  onClick={() => setSelectedEntry(entry)}
                  className={`p-2.5 rounded-lg border cursor-pointer transition-all space-y-1.5 ${
                    isSelected
                      ? 'bg-[#091024] border-purple-500/70 shadow-[0_0_12px_rgba(168,85,247,0.15)]'
                      : 'bg-[#040712] border-slate-800 hover:border-slate-700'
                  }`}
                >
                  {/* Top Bar: Title, Transition Badge & Author */}
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5 truncate max-w-[70%]">
                      <div className={`w-2 h-2 rounded-full ${entry.verifiedInAsm ? 'bg-emerald-400' : 'bg-rose-400'}`} />
                      <span className="font-bold text-white text-[9.5px] truncate">
                        {entry.conceptName}
                      </span>
                    </div>

                    <div className="flex items-center gap-1 shrink-0">
                      <span className="text-[8px] bg-purple-950/80 text-purple-300 px-1.5 py-0.2 rounded border border-purple-500/40 font-bold">
                        {entry.stateTransition.fromState} → {entry.stateTransition.toState}
                      </span>
                      <span className={`text-[7.5px] px-1 py-0.2 rounded font-bold ${
                        entry.author === 'C'
                          ? 'bg-cyan-950 text-cyan-300'
                          : entry.author === 'Si'
                          ? 'bg-emerald-950 text-emerald-300'
                          : 'bg-purple-950 text-purple-300'
                      }`}>
                        {entry.author}
                      </span>
                    </div>
                  </div>

                  {/* Description / Evidence Delta */}
                  <p className="text-[8.5px] text-slate-400 line-clamp-2 leading-tight">
                    {entry.stateTransition.evidenceDelta || entry.description}
                  </p>

                  {/* Modalities Badges */}
                  <div className="flex items-center gap-1 flex-wrap pt-0.5 text-[7.5px]">
                    {entry.modalities.interactiveUi && (
                      <span className="bg-cyan-950/80 text-cyan-300 px-1.5 py-0.2 rounded border border-cyan-600/50">
                        Dynamic UI
                      </span>
                    )}
                    {entry.modalities.audio && (
                      <span className="bg-emerald-950/80 text-emerald-300 px-1.5 py-0.2 rounded border border-emerald-600/50">
                        Audio {entry.modalities.audio.freqHz}Hz
                      </span>
                    )}
                    {entry.modalities.image && (
                      <span className="bg-purple-950/80 text-purple-300 px-1.5 py-0.2 rounded border border-purple-600/50">
                        SVG Manifold
                      </span>
                    )}
                    {entry.modalities.video && (
                      <span className="bg-pink-950/80 text-pink-300 px-1.5 py-0.2 rounded border border-pink-600/50">
                        Kinetic Video
                      </span>
                    )}
                    {entry.modalities.code && (
                      <span className="bg-amber-950/80 text-amber-300 px-1.5 py-0.2 rounded border border-amber-600/50">
                        Code ({entry.modalities.code.language})
                      </span>
                    )}
                  </div>

                  {/* Provenance Hash & Re-Instantiate Button */}
                  <div className="flex items-center justify-between border-t border-slate-800/80 pt-1 text-[8px] text-slate-500 font-mono">
                    <span className="truncate max-w-[55%]" title={entry.provenanceHash}>
                      Hash: <strong className="text-slate-400">{entry.provenanceHash.slice(0, 12)}...</strong>
                    </span>

                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleReinstantiateConcept(entry);
                      }}
                      className="text-cyan-400 hover:text-cyan-200 flex items-center gap-1 font-bold cursor-pointer"
                    >
                      <Play className="w-2.5 h-2.5" />
                      <span>Re-Instantiate</span>
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Selected Entry Deep Inspection Box */}
        {selectedEntry && (
          <div className="bg-[#040813] border border-cyan-500/30 rounded-lg p-2.5 text-[8.5px] space-y-1.5 font-mono shrink-0">
            <div className="flex items-center justify-between text-cyan-300 font-bold border-b border-slate-800 pb-1">
              <span className="flex items-center gap-1 uppercase">
                <Lock className="w-3 h-3 text-cyan-400" />
                Selected Provenance Witness Block
              </span>
              <span className="text-emerald-400">Step #{selectedEntry.stateTransition.step}</span>
            </div>

            <div className="grid grid-cols-2 gap-1 text-[8px] text-slate-400">
              <div>Concept ID: <span className="text-slate-200">{selectedEntry.conceptId.slice(0, 16)}...</span></div>
              <div>Parent Hash: <span className="text-slate-200">{selectedEntry.parentHash.slice(0, 12)}...</span></div>
              <div>Epistemic V(X): <span className="text-cyan-300 font-bold">({selectedEntry.epistemicPair[0]}, {selectedEntry.epistemicPair[1]})</span></div>
              <div>ASM Witness: <span className="text-emerald-300 font-bold">0x04 (STABLE)</span></div>
            </div>

            {selectedEntry.asmOpcodeWitness && (
              <div className="bg-black/80 p-1.5 rounded border border-slate-800 text-[8px] text-emerald-300">
                {selectedEntry.asmOpcodeWitness}
              </div>
            )}
          </div>
        )}
      </div>

    </div>
  );
};

