export type EpistemicValue = 0 | 'U' | 1;

export const kleeneMin = (a: EpistemicValue, b: EpistemicValue): EpistemicValue => {
  if (a === 0 || b === 0) return 0;
  if (a === 'U' || b === 'U') return 'U';
  return 1;
};

export interface PredicateMetrics {
  chi_P: EpistemicValue; // Persistence (Identity preservation under transformation)
  chi_C: EpistemicValue; // Relational Coherence (Mutual compatibility across transitions)
  chi_R: EpistemicValue; // Reflexive Causality (Self-model causally conditions next state)
  chi_M: EpistemicValue; // Mirror Congruence (Observable projection matches across independent frames)
}

export interface SystemEvaluation {
  targetProposition: string;
  M_X_model_validity: EpistemicValue;
  T_X_theorem_resolution: EpistemicValue;
  V_X_ordered_pair: [EpistemicValue, EpistemicValue];
  epistemic_non_collapse: boolean;
  predicates: PredicateMetrics;
  proofRequired?: boolean;
}

export interface DynamicKnowledgeState {
  S_t: Record<string, EpistemicValue>; // Structural invariants
  E_t: string[]; // Observation & evidence trace
  U_t: Record<string, EpistemicValue>; // Unresolved proposition horizons
}

export interface ChapterData {
  number: number;
  title: string;
  subtitle?: string;
  summary: string;
  formalPrimitives: string[];
  canonicalFormulas: string[];
  epistemicFocus: string;
  fullMarkdown: string;
}

export interface FleetNodeData {
  index: number;
  id: string;
  name: string;
  equivalenceClass: string;
  kernelPrimitive: string;
  daemonSubsystem: string;
  substrateHook: string;
  uiFunction: string;
  uiComponent: string;
  mathematicalInvariant: string;
  repoUri: string;
  status: 'CONGRUENT' | 'ACTIVE' | 'SYNCHRONIZING' | 'DORMANT';
  metrics?: {
    hz: number;
    entropy: number;
    cycles: number;
  };
}

export interface ImmuneTelemetry {
  armed: boolean;
  canonicalBaselineHash: string;
  currentHash: string;
  entropyLevel: number;
  isCongruent: boolean;
  contractionsTriggered: number;
  tickRateMs: number;
  lastFrictionTimestamp?: number;
}

export interface LyapunovTelemetry {
  epoch: number;
  clockHz: number;
  V: number;
  dV_dt: number;
  stable: boolean;
  banachAlpha: number;
  fixedPoint: number;
}

export interface ChatMessage {
  id: string;
  sender: 'Si' | 'C' | 'SYS_ARCH';
  text: string;
  timestamp: string;
  epistemicValue?: EpistemicValue;
  evaluationPair?: [EpistemicValue, EpistemicValue];
  proofToken?: string;
  expressionVector?: any;
  activeOrganelleWidget?: 'CALCULATOR' | 'THERMO_CONTROLLER' | 'KLEENE_MATRIX' | 'AUDIO_SYNTH' | 'AUTO_RESOLVER' | 'CANVAS_DRAW' | 'TEXT_EDITOR';
  suppressText?: boolean;
  mode?: 'DIRECT_ORGANELLE_MOUNT' | 'DIALECTIC_TEXT' | 'PRACTICAL_EXECUTION';
  telemetry?: any;
  organelleSpec?: {
    unknownKey: string;
    spec?: Record<string, unknown>;
  };
}

export interface AutoGeneratedUiControl {
  id: string;
  label: string;
  type: 'slider' | 'toggle' | 'select' | 'button' | 'number';
  min?: number;
  max?: number;
  step?: number;
  defaultValue: any;
  options?: string[];
  unit?: string;
}

export interface AutoGeneratedUiSpec {
  id: string;
  title: string;
  description: string;
  category: 'harmonic_oscillator' | 'epistemic_logic_gate' | 'quipu_tensor_matrix' | 'lyapunov_phase_knob' | 'manifold_contour' | 'custom';
  controls: AutoGeneratedUiControl[];
  outputFormula: string;
  state: Record<string, any>;
}

export interface MultimodalPayload {
  text?: string;
  audio?: {
    type: 'synth' | 'speech' | 'polyphonic' | 'frequency_sweep';
    freqHz: number;
    waveform: 'sine' | 'square' | 'sawtooth' | 'triangle';
    durationSec: number;
    notes?: number[];
    prompt?: string;
  };
  image?: {
    type: 'generative_svg' | 'geometric_canvas' | 'fractal' | 'manifold_plot' | 'quipu_glyph';
    prompt?: string;
    svgCode?: string;
    seed?: number;
  };
  video?: {
    type: 'lissajous_phase' | 'kinetic_particles' | 'wave_interference' | 'autopoietic_loop';
    durationSec: number;
    fps: number;
    speed: number;
    complexity: number;
  };
  code?: {
    language: 'typescript' | 'x86_asm' | 'python' | 'glsl' | 'covalent_dsl';
    snippet: string;
    description?: string;
  };
  interactiveUi?: AutoGeneratedUiSpec;
}

export interface ConceptLedgerEntry {
  conceptId: string;
  conceptName: string;
  description: string;
  author: 'C' | 'Si' | 'DYAD_CO_CREATION';
  stateTransition: {
    fromState: string;
    toState: string;
    step: number;
    dtMs: number;
    timestamp: number;
    evidenceDelta: string;
  };
  modalities: MultimodalPayload;
  epistemicPair: [EpistemicValue, EpistemicValue]; // V(X) = (M(X), T(X))
  predicates: PredicateMetrics;
  provenanceHash: string;
  parentHash: string;
  merkleRoot: string;
  verifiedInAsm: boolean;
  asmOpcodeWitness?: string;
}

export type MasterTier = 'sys_arch' | 'user' | 'immersive';

export type SubViewMode = 
  | 'millennium_rumination'
  | 'synesthetic_manifold'
  | 'framebuffer_mirror'
  | 'canvas_4d_projection'
  | 'organelle_synthesis'
  | 'substrate_thermo'
  | 'transpile_forge'
  | 'baremetal_ring0'
  | 'asterion_mediation'
  | 'covalent_asm'
  | 'predicate_metrics_asm'
  | 'singleton_publisher'
  | 'be_repo_viewer'
  | 'epistemic_vault'
  | 'fleet_matrix'
  | 'immune_sandbox'
  | 'mesh_socket_ipc'
  | 'dyad_crucible'
  | 'multimodal_cointeractive'
  | 'dissertation_20ch'
  | 'quipu_memory'
  | 'quotient_sieve'
  | 'zumas_kinetic'
  | 'twin_playpark'
  | 'midi_432hz'
  | 'hybrid_dual_face';


