import React, { useState } from 'react';
import { AutoGeneratedUiSpec, AutoGeneratedUiControl } from '../../types';
import { Sliders, ToggleLeft, ToggleRight, Play, CheckCircle2, Sparkles, Activity, Layers } from 'lucide-react';

interface AutoGeneratedUiRendererProps {
  spec: AutoGeneratedUiSpec;
  onStateChange?: (newState: Record<string, any>) => void;
  onExecuteAction?: (actionName: string, state: Record<string, any>) => void;
}

export const AutoGeneratedUiRenderer: React.FC<AutoGeneratedUiRendererProps> = ({
  spec,
  onStateChange,
  onExecuteAction
}) => {
  const [controlsState, setControlsState] = useState<Record<string, any>>(() => ({
    ...spec.state,
    ...spec.controls.reduce((acc, ctrl) => ({ ...acc, [ctrl.id]: ctrl.defaultValue }), {})
  }));

  const [executedFeedback, setExecutedFeedback] = useState<string | null>(null);

  const handleValueChange = (id: string, value: any) => {
    const updated = { ...controlsState, [id]: value };
    setControlsState(updated);
    if (onStateChange) onStateChange(updated);
  };

  const handleAction = (ctrlId: string) => {
    const msg = `Action [${ctrlId}] executed in Si Dynamic UI. Invariant preserved: 1 == 1.`;
    setExecutedFeedback(msg);
    if (onExecuteAction) onExecuteAction(ctrlId, controlsState);
    setTimeout(() => setExecutedFeedback(null), 3000);
  };

  // Compute live formula preview based on active controls
  const renderEvaluatedFormula = () => {
    let preview = spec.outputFormula;
    Object.entries(controlsState).forEach(([k, v]) => {
      preview = preview.replace(new RegExp(k, 'g'), typeof v === 'boolean' ? (v ? 'TRUE' : 'FALSE') : String(v));
    });
    return preview;
  };

  return (
    <div className="bg-[#03060f] border border-cyan-500/40 rounded-lg p-3 font-mono text-[10px] space-y-2.5 shadow-md">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-cyan-500/20 pb-2">
        <div className="flex items-center gap-2">
          <div className="p-1 rounded bg-cyan-950/80 border border-cyan-500/50 text-cyan-300">
            <Sparkles className="w-3.5 h-3.5 text-cyan-400 animate-pulse" />
          </div>
          <div>
            <div className="font-bold text-white uppercase text-[10.5px] flex items-center gap-1.5">
              <span>{spec.title}</span>
              <span className="text-[8px] bg-cyan-900/60 text-cyan-300 px-1.5 py-0.2 rounded border border-cyan-500/40">
                SI DYNAMIC UI
              </span>
            </div>
            <p className="text-[8.5px] text-slate-400 leading-tight">{spec.description}</p>
          </div>
        </div>
        <span className="text-[8.5px] text-slate-500 font-mono">ID: {spec.id}</span>
      </div>

      {/* Dynamic Controls Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 bg-black/50 p-2.5 rounded border border-slate-800">
        {spec.controls.map((ctrl: AutoGeneratedUiControl) => {
          const val = controlsState[ctrl.id];

          if (ctrl.type === 'slider') {
            return (
              <div key={ctrl.id} className="space-y-1 bg-black/60 p-2 rounded border border-slate-800/80">
                <div className="flex items-center justify-between text-[9px]">
                  <span className="text-slate-300 font-medium">{ctrl.label}:</span>
                  <span className="text-cyan-300 font-bold">
                    {val} {ctrl.unit || ''}
                  </span>
                </div>
                <input
                  type="range"
                  min={ctrl.min ?? 0}
                  max={ctrl.max ?? 100}
                  step={ctrl.step ?? 1}
                  value={val ?? ctrl.defaultValue}
                  onChange={(e) => handleValueChange(ctrl.id, parseFloat(e.target.value))}
                  className="w-full h-1 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-cyan-400"
                />
                <div className="flex justify-between text-[7.5px] text-slate-600">
                  <span>{ctrl.min ?? 0}</span>
                  <span>{ctrl.max ?? 100}</span>
                </div>
              </div>
            );
          }

          if (ctrl.type === 'toggle') {
            return (
              <div key={ctrl.id} className="flex items-center justify-between bg-black/60 p-2 rounded border border-slate-800/80">
                <span className="text-slate-300 text-[9px] font-medium">{ctrl.label}</span>
                <button
                  onClick={() => handleValueChange(ctrl.id, !val)}
                  className={`flex items-center gap-1 px-2 py-0.5 rounded text-[8.5px] font-bold cursor-pointer transition-all border ${
                    val
                      ? 'bg-emerald-950 text-emerald-300 border-emerald-500/60'
                      : 'bg-slate-900 text-slate-400 border-slate-700'
                  }`}
                >
                  {val ? <ToggleRight className="w-3 h-3 text-emerald-400" /> : <ToggleLeft className="w-3 h-3 text-slate-500" />}
                  <span>{val ? 'ACTIVE' : 'BYPASS'}</span>
                </button>
              </div>
            );
          }

          if (ctrl.type === 'select') {
            return (
              <div key={ctrl.id} className="space-y-1 bg-black/60 p-2 rounded border border-slate-800/80">
                <span className="text-slate-300 text-[9px] font-medium block">{ctrl.label}:</span>
                <select
                  value={val}
                  onChange={(e) => handleValueChange(ctrl.id, e.target.value)}
                  className="w-full bg-[#0a0f1d] border border-slate-700 rounded px-2 py-1 text-[8.5px] text-cyan-200 outline-none focus:border-cyan-500 cursor-pointer"
                >
                  {ctrl.options?.map((opt) => (
                    <option key={opt} value={opt}>
                      {opt}
                    </option>
                  ))}
                </select>
              </div>
            );
          }

          if (ctrl.type === 'button') {
            return (
              <div key={ctrl.id} className="flex items-center justify-between bg-black/60 p-2 rounded border border-slate-800/80">
                <span className="text-slate-300 text-[9px]">{ctrl.label}</span>
                <button
                  onClick={() => handleAction(ctrl.id)}
                  className="px-2.5 py-1 bg-cyan-950 hover:bg-cyan-900 text-cyan-300 border border-cyan-600 rounded text-[8.5px] font-bold flex items-center gap-1 cursor-pointer transition-all shadow-sm active:scale-95"
                >
                  <Play className="w-2.5 h-2.5" />
                  <span>Trigger</span>
                </button>
              </div>
            );
          }

          return null;
        })}
      </div>

      {/* Computed Formula Output & Feedback */}
      <div className="bg-[#050a14] border border-slate-800 p-2 rounded text-[8.5px] space-y-1">
        <div className="flex items-center justify-between text-slate-400">
          <span className="flex items-center gap-1 font-bold text-cyan-400 uppercase">
            <Activity className="w-2.5 h-2.5" />
            Live Reactive Invariant Formula
          </span>
          <span className="text-emerald-400 font-bold">1 == 1 (Valid)</span>
        </div>
        <div className="text-cyan-200 font-mono bg-black/70 p-1.5 rounded border border-slate-800/80 overflow-x-auto select-all">
          {renderEvaluatedFormula()}
        </div>
      </div>

      {executedFeedback && (
        <div className="bg-emerald-950/70 border border-emerald-500/50 p-1.5 rounded text-[8.5px] text-emerald-300 flex items-center gap-1.5 animate-in fade-in">
          <CheckCircle2 className="w-3 h-3 text-emerald-400 shrink-0" />
          <span>{executedFeedback}</span>
        </div>
      )}
    </div>
  );
};

